# Name for your service on Render
service: blog-api

# Build command to install dependencies (replace if needed)
build:
  # Replace 'requirements.txt' with your actual file name if different
  cmd: pip install -r requirements.txt

# Start command to run your Django application
web:
  # Assuming your WSGI entry point is in blog/wsgi.py
  cmd: gunicorn blog.wsgi:application
  # Increase workers if needed based on your application's requirements
  concurrency: 2

# Database configuration (assuming you have SQLite set up)
env:
  # Set the database connection string
  DATABASE_URL: sqlite:///blog.db