# Generated by Django 4.2.6 on 2024-08-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_blog_is_main_slider_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_breaking',
            field=models.BooleanField(default=False),
        ),
    ]
