# Generated by Django 4.2.6 on 2024-08-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_blog_is_breaking'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
