# Generated by Django 4.2.6 on 2024-08-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_blog_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_top_three',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
