# Generated by Django 4.2.6 on 2024-09-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_socialmedia_alter_blog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True)),
                ('address_1', models.TextField(blank=True, null=True)),
                ('address_2', models.TextField(blank=True, null=True)),
                ('address_3', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('zipcode', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
