# Generated by Django 4.2.6 on 2024-09-17 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='WebAddress',
        ),
    ]
