# Generated by Django 4.2.6 on 2024-10-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_comment_user_comment_email_comment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_slider_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
