# Generated by Django 4.2.6 on 2024-08-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdSense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_client', models.CharField(help_text='Your Google AdSense client ID (e.g., ca-pub-XXXXXXXXXXXXXXX)', max_length=100)),
                ('ad_slot', models.CharField(help_text='Your Google AdSense ad slot ID (e.g., 1234567890)', max_length=100)),
                ('ad_format', models.CharField(choices=[('auto', 'Auto'), ('responsive', 'Responsive'), ('fixed', 'Fixed')], default='auto', help_text='Format of the AdSense ad (e.g., Auto, Responsive, Fixed)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to activate or deactivate this ad.')),
                ('description', models.CharField(blank=True, help_text='A short description for internal reference.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Google AdSense',
                'verbose_name_plural': 'Google AdSense Ads',
            },
        ),
    ]
